import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Header from "@/app/components/Header";
import MoviesSearch from "@/app/components/MoviesSearch";
import { Suspense } from "react";
import Loading from "./loading";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          <Navbar />
          <MoviesSearch />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
